spring.application.name=NotificationService

server.port=8083

# Kafka

spring.kafka.bootstrap-servers=localhost:9092

# Email Configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL_ADDRESS
spring.mail.password=YOUR_EMAIL_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true